### ISSUE TITLE
Weekly report updates squash the username field of previous updates from another user.

### ISSUE THREAD

**Issue by asteffes-mfp** [etsy/opsweekly#40]
Not sure if this is intentional or not but we noticed that if user A classifies and notates some events, and then user B goes to do the same for some new events (say, on the following day), user A's updates will be re-labeled as being from user B. Are we just doing it wrong (ie, can only one person update the list for the week?) or did we discover a bug?]

**Comment by lozzd** [comment]
That is "by design", unfortunately. The system deals with a single person being on call per time period (by default, a week). The concept of a week is so deeply ingrained, it might be difficult to do anything else.

**Comment by asteffes-mfp** [comment]
Understood and thank you. The week issue isn't a problem for us. We would like to use Opsweekly in an environment with developers and ops people who share the on-call workload, where either group might need to update their own alerts. Perhaps we'll have one per team (unless other folks watching this issue have a better solution already.)

**Comment by lozzd** [comment]
Ah yes, so that's a great example of why we added per team support. We totally support dev and ops sharing the on call load... All of those teams have their own "opsweekly" since the workload differs. E.g., searchweekly, opsweekly, etc etc. You can share one instance, and set up a wildcard vhost. 

Please reopen and let em know if there is anything else!
